# Generated by Django 5.2.7 on 2025-10-17 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_bn",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Номер СЗ"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма заказа",
                    ),
                ),
                (
                    "folder_bn",
                    models.URLField(
                        blank=True,
                        help_text="Формат: \\\\server\\share\\folder или file:///C:/Path/To/Folder/",
                        verbose_name="Ссылка на папку с СЗ",
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("at_work", "В работе"),
                            ("completed", "Выполнен"),
                            ("annulled", "Аннулирован"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "folder_documentation",
                    models.URLField(
                        blank=True,
                        help_text="Формат: \\\\server\\share\\folder или file:///C:/Path/To/Folder/",
                        verbose_name="Ссылка на папку с документацией",
                    ),
                ),
                (
                    "date_completion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заказчик"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="TrackingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Внутренний номер",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        max_length=255, verbose_name="Наименование и номер номенклатуры"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "date_shipment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата отгрузки"
                    ),
                ),
                (
                    "date_entry_1c",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата занесения в 1С"
                    ),
                ),
                (
                    "date_transfer_to_pdd",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата передачи СЗ в ПДО"
                    ),
                ),
                (
                    "pps_cp",
                    models.CharField(
                        choices=[
                            ("not_need", "Не требуется"),
                            ("check", "Проверить"),
                            ("make", "Сделать"),
                            ("done", "Сделано"),
                        ],
                        default="not_need",
                        max_length=9,
                        verbose_name="РТК+УП",
                    ),
                ),
                (
                    "order_number_1c",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Номер заказа в 1С",
                    ),
                ),
                (
                    "date_transfer_to_ss",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата передачи СЗ в службу снабжения",
                    ),
                ),
                (
                    "date_warehouse",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата поступления на склад заготовок, металла",
                    ),
                ),
                (
                    "date_tentative_supply",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Предварительные сроки поставки заготовок, металла",
                    ),
                ),
                (
                    "status_product",
                    models.CharField(
                        choices=[
                            ("start", "Запущен"),
                            ("waiting_billet", "Ожидает поставки заготовки"),
                            ("at_work", "В работе"),
                            ("completed", "Выполнен"),
                            ("annulled", "Аннулирован"),
                        ],
                        default="start",
                        max_length=15,
                        verbose_name="Статус производства",
                    ),
                ),
                (
                    "date_completion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_table",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция отслеживания",
                "verbose_name_plural": "Главная таблица отслеживания",
                "ordering": ["order", "product"],
            },
        ),
    ]
