# Generated by Django 5.2.7 on 2025-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-number_bn"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="folder_bn",
            field=models.CharField(
                blank=True,
                help_text="Формат: \\\\server\\share\\folder или C:\\Path\\To\\Folder\\ ",
                max_length=500,
                null=True,
                verbose_name="Ссылка на папку с СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="folder_documentation",
            field=models.CharField(
                blank=True,
                help_text="Формат: \\\\server\\share\\folder или C:\\Path\\To\\Folder\\ ",
                max_length=500,
                null=True,
                verbose_name="Ссылка на папку с документацией",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="number_bn",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер СЗ"),
        ),
        migrations.AlterField(
            model_name="trackingtable",
            name="status_product",
            field=models.CharField(
                choices=[
                    ("start", "Запущен"),
                    ("waiting_billet", "Ожид.Пост.Загот."),
                    ("at_work", "В работе"),
                    ("completed", "Выполнен"),
                    ("annulled", "Аннулирован"),
                ],
                default="start",
                max_length=15,
                verbose_name="Статус производства",
            ),
        ),
    ]
